edge_routers:
  data:
    device_type: router
    tier: edge

core_switches:
  data:
    device_type: switch
    tier: core

production:
  data:
    environment: production

datacenter-01:
  data:
    location: US-EAST-1
