---
# Sample hosts configuration file
# Replace with your actual network devices

R1:
  hostname: 192.168.100.101
  platform: ios
  username: cisco
  password: cisco
  groups:
    - cisco_ios
  data:
    role: core_router

R2:
  hostname: 192.168.100.102
  platform: ios
  username: cisco
  password: cisco
  groups:
    - cisco_ios
  data:
    role: core_router

R3:
  hostname: 192.168.100.103
  platform: ios
  username: cisco
  password: cisco
  groups:
    - cisco_ios
  data:
    role: core_router